OBJ = module.o sparse.o pn_aux.o math_lib.o mgmres.o  \
		  readHmnR.o inverse.o proteus.o \
       eigen.o ham_qlayer2qlayer.o psi.o rand.o \
  		 ham_slab.o ham_bulk.o gonze_nac.o ek_slab.o ek_bulk_polar.o ek_bulk.o \
       readinput.o fermisurface.o surfgreen.o surfstat.o \
  		 mat_mul.o ham_ribbon.o ek_ribbon.o \
       fermiarc.o berrycurvature.o \
  		 wanniercenter.o dos.o  orbital_momenta.o \
		 berry.o wanniercenter_adaptive.o \
  		 effective_mass.o findnodes.o \
	main.o

# compiler
F90  = mpif90 -fpp -DMPI -fpe3 -O3 -DARPACK -DINTELMKL -fallow-argument-mismatch 
#F90  = ifort -fpp  -DINTELMKL -fpe3 -check all -traceback -g
CC = mpicc -cpp -O3 -DINTELMKL 

INCLUDE = -I${MKLROOT}/include
WFLAG = -nogen-interface
OFLAG = -O3 -static-intel
FFLAG = $(OFLAG) $(WFLAG)
LFLAG = $(OFLAG)

# ARPACK LIBRARY
ARPACK=-L/usr/local/lib -larpack


# blas and lapack libraries
# static linking
#LIBS = -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a \
        ${MKLROOT}/lib/intel64/libmkl_sequential.a \
        ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl \
		  ${ARPACK}

# dynamic linking
LIBS = ${ARPACK} -L/${MKLROOT}/lib/intel64 -lmkl_core -lmkl_sequential -lmkl_intel_lp64 -lpthread 
 
main : $(OBJ)
	$(F90) $(LFLAG) $(OBJ) -o pn.x $(LIBS)
	cp -f pn.x ../bin

.SUFFIXES: .o .f90 .c

.f90.o :
	$(F90) $(FFLAG) $(INCLUDE) -c $*.f90

clean :
	rm -f *.o *.mod *~ pn.x

